version: '3.8'

services:
  db:
    image: postgres
    env_file: '.env'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres --quiet" ]
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    image: api:latest
    env_file: '.env'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "main.py"]

networks:
  default:
    name: service_network

